version: 2.1

orbs:
  maven: circleci/maven@1.0.1
  heroku: circleci/heroku@1.0.1

workflows:
  build: # build, test, resolve dependencies, and deploy if branch is main
    jobs:
      - maven/test:
          context: kgrid
          settings_file: ".circleci/settings.xml"
  earlymorning: # build and deploy main at the crack-o-dawn
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - maven/test:
          context: kgrid
          settings_file: ".circleci/settings.xml"
  #    - heroku/deploy-via-git:
  #        context: kgrid
  #        requires:
  #          - maven/test
      - deploy-to-heroku:
          context: kgrid
          executor: heroku/default
          steps:
            - checkout
            - heroku/install
            - heroku/deploy-via-git:
                force: true

# Don't force push unless necessary
# Use: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $CIRCLE_BRANCH:master
# The heroku env tokens are generated using `heroku` CLI; `CIRCLE_BRANCH` is `main`
#jobs:
#  deploy-to-heroku:
#    executor: heroku/default
#    steps:
#      - checkout
#      - heroku/install
#      - heroku/deploy-via-git:
#          force: true
